# Generated by Django 3.0.3 on 2020-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='employment',
            field=models.CharField(default='Unspecified', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='Unspecified', max_length=50, null=True),
        ),
    ]
